# Generated by Django 5.2.7 on 2025-11-02 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('product_description', models.TextField(validators=[django.core.validators.MinLengthValidator(30)])),
                ('product_price', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
