# Generated by Django 5.2.7 on 2025-11-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
